name: Test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    # Replace with specific GitHub user ?
      contents: write
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
          token: ${{ secrets.PAT }}

      - name: Output file
        run: |
          cat test.txt

      - name: Append test to file
        run: |
          echo 'CHANGELOG ' >> test.txt

      - name: Output file
        run: |
          cat test.txt

      - name: Get last commit message
        id: last-commit-message
        run: |
            echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Commit changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.last-commit-message.outputs.msg }}
          commit_options: '--amend --no-edit'
          push_options: '--force'
          skip_fetch: true      

      
